window.game.unitData["witch"] = {
	hp:30,
	regen:0,
	spMultiplier:1,
	meleePower:4,
	rangedPower:4,
	physicalPower:1,
	magicPower:10,
	pierce:0,
	drain:0,
	meleeDefense:1,
	rangedDefense:5,
	physicalDefense:1,
	magicDefense:6,
	spikes:0,
	speed:4,
	force:10,
	weight:5,
	intelligence:0,
	actions:["magicattack", "dodge", "rush"],
	actionChances:[50, 30, 20],
	attackType:"magic",
	rangedAttack:true,
	rangedAttackRate:200,
	rangedActions:["magic"],
	rangedActionChances:[100],
	wrecker:false,
	raider:false,
	defender:false,
	initiative:false,
	superType:"action",
	superLength:20,
	superData:function(user){
		user.spMultiplier = 0;
		user.meleePower += 6;
	},
	restricted:false,
	restrictedToUsers:[]
};