window.game.unitData["cornchip"] = {
	hp:30,
	regen:0,
	spMultiplier:1,
	meleePower:9,
	rangedPower:0,
	physicalPower:6,
	magicPower:0,
	pierce:1,
	drain:0,
	meleeDefense:1,
	rangedDefense:1,
	physicalDefense:1,
	magicDefense:1,
	spikes:2,
	speed:5,
	force:10,
	weight:0,
	intelligence:0,
	actions:["attack", "block", "rush"],
	actionChances:[50, 20, 30],
	attackType:"physical",
	rangedAttack:false,
	rangedAttackRate:0,
	rangedActions:[],
	rangedActionChances:[],
	wrecker:false,
	raider:false,
	defender:false,
	initiative:false,
	superType:"action",
	superLength:20,
	superData:function(user){
		user.regen = 0.1;
		user.spMultiplier = 0;
	},
	restricted:false,
	restrictedToUsers:[]
};